default_language_version:
  python: python 3.10
default_stages: [pre-commit, pre-push]
repos:
-  repo: https://github.com/pre-commit/pre-commit-hooks
   rev: v4.5.0
   hooks:
   -  id: check-yaml
   -  id: requirements-txt-fixer
   -  id: no-commit-to-branch
      args: ['--branch', 'main',]
-  repo: https://github.com/pre-commit/mirrors-autopep8
   rev: 'v2.0.4'
   hooks:
   -  id: autopep8
-  repo: https://github.com/PyCQA/flake8
   rev: 7.0.0
   hooks:
   -  id: flake8
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.13
  hooks:
    - id: ruff
    - id: ruff-format
      args: ['--line-length', '79']
